name: Update Submodules
on:
  repository_dispatch:
    types: [repository-dispatch-event]
jobs:
  dispatchEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: 'recursive'
      - run: |
          git config --global user.name "Gaurav Chaudhari"
          git config --global user.email "gaurav.chaudhari@seagate.com" 
      - run: git submodule update --remote --checkout
      - run: git add --all
      - run: git commit -m "Automated submodule remote update"
      - run: git push origin master 
